INSERT INTO cast (id, movie_id, cast) VALUES (1,  1, 'Tim Robbins')
INSERT INTO cast (id, movie_id, cast) VALUES (2,  1, 'Morgan Freeman')
INSERT INTO cast (id, movie_id, cast) VALUES (3,  1, 'Bob Gunton')
INSERT INTO cast (id, movie_id, cast) VALUES (4,  2, 'Tom Hanks')
INSERT INTO cast (id, movie_id, cast) VALUES (5,  2, 'Robin Wright Penn')
INSERT INTO cast (id, movie_id, cast) VALUES (6,  2, 'Gary Sinise')
INSERT INTO cast (id, movie_id, cast) VALUES (7,  3, '张国荣')
INSERT INTO cast (id, movie_id, cast) VALUES (8,  3, '张丰毅')
INSERT INTO cast (id, movie_id, cast) VALUES (9,  4, 'Jean Reno')
INSERT INTO cast (id, movie_id, cast) VALUES (10, 4, 'Natalie Portman')
INSERT INTO cast (id, movie_id, cast) VALUES (11, 4, 'Gary Oldman')
INSERT INTO cast (id, movie_id, cast) VALUES (12, 4, 'Danny Aiello')
INSERT INTO cast (id, movie_id, cast) VALUES (13, 4, 'Peter Appel')
INSERT INTO cast (id, movie_id, cast) VALUES (14, 4, 'Michael Badalucco')
INSERT INTO cast (id, movie_id, cast) VALUES (15, 5, 'Roberto Benigni')
INSERT INTO cast (id, movie_id, cast) VALUES (16, 5, 'Nicoletta Braschi')
INSERT INTO cast (id, movie_id, cast) VALUES (17, 5, 'Giorgio Cantarini')
